### ISSUE TITLE
UnicodeDecodeError - 'utf8' codec can't decode byte 0x90 in position 41: invalid start byte

### ISSUE THREAD

**Issue by juliusosokinas** [ExCiteS/geokey-sapelli#25]
Stack trace can be seen on Opbeat: https://opbeat.com/excites/geokey-community-maps/errors/5/

**Comment by mstevens83** [comment]
Oops, do we know who uploaded the file? If I can get the csv I van debug.

**Comment by EmpressNaledi** [comment]
I think I did by mistake. I tried uploading the zip instead of the csv

**Comment by mstevens83** [comment]
Oh, that would definitely explain a thing or too ;-).
But it should not have crashed though. I'll add some more exception handling so can avoid such crashes and show a more graceful error message instead (something like "this does not appear to be a valid CSV file").

**Comment by EmpressNaledi** [comment]
That would definitely help the user!

**Comment by juliusosokinas** [comment]
Might be worth doing some little changes on the front-end: http://www.w3schools.com/tags/att_input_accept.asp

**Comment by mstevens83** [comment]
I've been unable to reproduce the crash (as logged on opbeat) when uploading a big zip file instead of a csv. I get a rather graceful error message and not a crash (+ there's nothing new on opbeat). So I'm beginning to doubt whether it was Louise's zip upload which caused the crash. So could it have been someone else uploading a corrupt CSV? Gill perhaps?
Without a file to debug with there's not much I can do though.

**Comment by mstevens83** [comment]
I did add the `accept` attributes Julius suggested (673811b).

**Comment by juliusosokinas** [comment]
On Opbeat you can see the user who was making a request. And I see it's Louise :) Cheers, I guess attributes will be enough!
