### ISSUE TITLE
Detect and warn about "project clashes"

### ISSUE THREAD

**Issue by mstevens83** [ExCiteS/geokey-sapelli#26]

**Comment by juliusosokinas** [comment]
The problem is, that Sapelli app gets the project ID (used to upload data), using this endpoint:

`http://play.geokey.org.uk/api/sapelli/projects/description/xxxx/yyyyyyy`

Where xxxx = Sapelli Project ID; yyyyyyy = Sapelli Project Fingerprint

If the same Sapelli project was uploaded by another user, it will get wrong project ID (because it will return the first match).

Possibly solution is to retrieve a project, based on the following criteria, but only where user can contribute. However, if user upload the same project himself (or he is granted permissions to another project ending up with two project using the same Sapelli project), the conflict still persists.

@michalis-vitos & @julia-altenbuchner, please add other thoughts if something comes up.

**Comment by juliusosokinas** [comment]
Another solution would be to allow upload Sapelli project only once (with the same ID and fingerprint).

**Comment by juliusosokinas** [comment]
The last solution was implemented - Sapelli project is allowed to be uploaded only once, unless the Sapelli project ID is changed.
