### ISSUE TITLE
Leave empty descriptions "empty" instead of setting "None"

### ISSUE THREAD

**Issue by juliusosokinas** [ExCiteS/geokey-sapelli#28]

**Comment by mstevens83** [comment]
Ok, I can do that.

**Comment by mstevens83** [comment]
Hmm, this is strange, seems like I already set it to empty string (`''`) rather than `None`: https://github.com/ExCiteS/geokey-sapelli/blob/master/geokey_sapelli/helper/project_mapper.py#L46
Perhaps you are looking at an old project? Maybe we can add a migration to replace any `None` descriptions with `''`.

**Comment by juliusosokinas** [comment]
Yes, might be I noticed that on old project! I might write a small unit test to make sure it's not set to a string "None". Unless you want to do that? :)

**Comment by mstevens83** [comment]
Go ahead ;-)
