### ISSUE TITLE
File encoding issue on importing Sapelli CSV files

### ISSUE THREAD

**Issue by michalis-vitos** [ExCiteS/geokey-sapelli#4]
Sapelli outputs records to CSV with UTF-8-BOM encoding, which seems to cause errors when imported by the Geokey Sapelli plugin. When the files were converted to UTF-8, the import worked with no issues.

**Comment by mfc-julius** [comment]
Might quickly help: http://stackoverflow.com/questions/8898294/convert-utf-8-with-bom-to-utf-8-with-no-bom-in-python.

**Comment by mstevens83** [comment]
Using the BOM (=byte order marker) is probably not strictly necessary on CSVs, but still a good idea. So I'd rather fix this on the Python side, I'll have a look to see if we can integrate the code Julius linked to.

**Comment by mstevens83** [comment]
There are in fact 2 problems to be dealt with:
- Python's standard csv.DictReader class doesn't detect the UTF8 BOM and therefore our parsing code fails on such files (because the BOM is taken as part of the first header field)
- but beyond that, the csv.DictReader class doesn't deal properly with UTF8 at all, meaning that even if we strip the BOM away we still can't guarantee textual data will be parsed correctly if it contains non-ascii characters.
I'm about to commit a solution to which tackles both of these problems.

**Comment by mstevens83** [comment]
All known unicode problems are fixed (& test for!) in https://github.com/ExCiteS/geokey-sapelli/releases/tag/0.5.0.
